- CHANGELOG.md
- azure-pipelines.yml
- tests/Unit/Public/New-InvalidArgumentException.Tests.ps1
- tests/Unit/Public/New-InvalidOperationException.Tests.ps1
- tests/Unit/Public/New-InvalidResultException.Tests.ps1
- tests/Unit/Public/New-NotImplementedException.Tests.ps1
- tests/Unit/Public/New-ObjectNotFoundException.Tests.ps1
This PR changes the Windows VM image used in the CI pipeline from 'win1803' to 'windows-2019'. This is because 'win1803' has been deprecated in Azure DevOps.
It also fixes the `New-*Exception` function unit tests to work correctly on PowerShell version 5, 6 and 7.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.common/18)
> Change Pipeline Windows VM Image to windows-2019 and Fix Exception Unit Tests

- CHANGELOG.md
- source/Public/Get-LocalizedData.ps1
This PR adds a default value of `en-US` to the `DefaultUICulture` parameter of the `Get-LocalizedData` function.
- Fixes #33 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.common/34)
> Get-LocalizedData: Add DefaultUICulture Default Parameter

- CHANGELOG.md
- source/Public/Get-LocalizedData.ps1
- tests/Unit/Public/Get-LocalizedData.Tests.ps1
- `Get-LocalizedData`
- Now correct evaluates the default UI culture
on non-English operating systems ([issue #50](https://github.com/dsccommunity/DscResource.Common/issues/50).
- If the LCID 127 is found it will be skipped and instead use the default
UI culture (which is `'en-US'` unless specified) ([issue #11](https://github.com/dsccommunity/DscResource.Common/issues/11).
- Fixes #11
- Fixes #50
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Get-LocalizedData: Improve on non-English operating systems

- CHANGELOG.md
- source/Public/Test-DscParameterState.ps1
- tests/Unit/Public/Test-DscParameterState.Tests.ps1
- Correction to `Test-DscParameterState` returning false positive when parameter
with an empty array is passed in `DesriedValues` or `CurrentValues` - fixes
[issue #53](https://github.com/dsccommunity/DscResource.Common/issues/53).
- Fixes #53
@johlju - would you mind reviewing this one when you have time?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.common/54)
> Fix False Positive in Test-DscParameterState with Empty Array Parameter

- CHANGELOG.md
- source/Public/Compare-DscParameterState.ps1
- source/Public/Test-DscParameterState.ps1
Correct typo of my last [PR](https://github.com/dsccommunity/DscResource.Common/pull/56).
Removing IncludeDesiredState and IncludeValue parameters in Test-DscParameterState.
I added those parameters to correct an exception when Compare-DscParameterState call Test-DscParameterState with splatting. 
But this was nonsense. 
Now, Compare-DscParameterState removes IncludeDesiredState and IncludeValue in splatting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Removing IncludeDesiredState and IncludeValue parameter in Test-DscParameterState and correct typo

- CHANGELOG.md
- README.md
- source/Public/Get-ComputerName.ps1
- tests/Integration/Public/Get-ComputerName.Tests.ps1
- tests/Unit/Public/Get-ComputerName.Tests.ps1
- Added cmdlet `Get-ComputerName` which can be used to returns the computer
name cross-plattform. The variable `$env:COMPUTERNAME` does not exist
cross-platform which hinders development and testing on macOS and Linux.
Instead this cmdlet can be used to get the computer name cross-plattform.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.common/60)
> Added cmdlet Get-ComputerName

- CHANGELOG.md
- source/Public/Compare-DscParameterState.ps1
- source/en-US/DscResource.Common.strings.psd1
- `Compare-DscParameterState`
- Fix verbose message to only show when using parameter `IncludeInDesiredState`.
Also made the verbose message more intuitive when the value being compared
was a `[System.Boolean]`.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.common/68)
> Compare-DscParameterState: Fix verbose message

- CHANGELOG.md
- README.md
- RequiredModules.psd1
- build.yaml
- source/Public/Assert-Module.ps1
- tests/Unit/Public/Assert-Module.Tests.ps1
- `Assert-Module`
- Now it possible to forcibly import a module using `-ImportModule -Force`
- It no longer outputs verbose messages that is normally generated when
using `Get-Module -ListAvailable` if the module that is asserted is
already in the session (issue #66).
- Fixes #66
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.common/67)
> Assert-Module: Reduce verbose output

- CHANGELOG.md
- RequiredModules.psd1
- build.yaml
- cocdecov.yml
- debug.ps1
- tests/Integration/Public/Set-DscMachineRebootRequired.Tests.ps1
- tests/Integration/Public/Set-PSModulePath.Tests.ps1
- tests/QA/module.tests.ps1
- tests/Unit/Private/Test-DscObjectHasProperty.Tests.ps1
- tests/Unit/Private/Test-DscPropertyState.Tests.ps1
- tests/Unit/Public/Assert-BoundParameter.Tests.ps1
- tests/Unit/Public/Assert-IPAddress.Tests.ps1
- tests/Unit/Public/Assert-Module.Tests.ps1
- tests/Unit/Public/Compare-DscParameterState.Tests.ps1
- tests/Unit/Public/Compare-ResourcePropertyState.Tests.ps1
- tests/Unit/Public/ConvertFrom-DscResourceInstance.Tests.ps1
- tests/Unit/Public/ConvertTo-CimInstance.Tests.ps1
- tests/Unit/Public/ConvertTo-Hashtable.Tests.ps1
- tests/Unit/Public/Get-ComputerName.Tests.ps1
- tests/Unit/Public/Get-LocalizedData.Tests.ps1
- tests/Unit/Public/Get-TemporaryFolder.Tests.ps1
- tests/Unit/Public/New-InvalidArgumentException.Tests.ps1
- tests/Unit/Public/New-InvalidDataException.Tests.ps1
- tests/Unit/Public/New-InvalidOperationException.Tests.ps1
- tests/Unit/Public/New-InvalidResultException.Tests.ps1
- tests/Unit/Public/New-NotImplementedException.Tests.ps1
- tests/Unit/Public/New-ObjectNotFoundException.Tests.ps1
- tests/Unit/Public/Remove-CommonParameter.Tests.ps1
- tests/Unit/Public/Test-DscParameterState.Tests.ps1
- tests/Unit/Public/Test-IsNanoServer.Tests.ps1
- Unit tests are now running using Pester 5 (issue #40).
- Excludes the PowerShell module script file _DscResource.Common.psm1_ located
in folder _source_ from the HQRM testing.
- Now code coverage is uploaded to codecov.io.
- Fixes #40
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.common/41)
> Unit tests are now running using Pester 5

- CHANGELOG.md
- RequiredModules.psd1
- build.yaml
- tests/QA/module.tests.ps1
- tests/Unit/Private/Test-DscObjectHasProperty.Tests.ps1
- tests/Unit/Private/Test-DscPropertyState.Tests.ps1
- tests/Unit/Public/Assert-BoundParameter.Tests.ps1
- tests/Unit/Public/Assert-IPAddress.Tests.ps1
- tests/Unit/Public/Assert-Module.Tests.ps1
- tests/Unit/Public/Compare-DscParameterState.Tests.ps1
- tests/Unit/Public/Compare-ResourcePropertyState.Tests.ps1
- tests/Unit/Public/ConvertFrom-DscResourceInstance.Tests.ps1
- tests/Unit/Public/ConvertTo-CimInstance.Tests.ps1
- tests/Unit/Public/ConvertTo-Hashtable.Tests.ps1
- tests/Unit/Public/Get-ComputerName.Tests.ps1
- tests/Unit/Public/Get-LocalizedData.Tests.ps1
- tests/Unit/Public/Get-TemporaryFolder.Tests.ps1
- tests/Unit/Public/New-InvalidArgumentException.Tests.ps1
- tests/Unit/Public/New-InvalidDataException.Tests.ps1
- tests/Unit/Public/New-InvalidOperationException.Tests.ps1
- tests/Unit/Public/New-InvalidResultException.Tests.ps1
- tests/Unit/Public/New-NotImplementedException.Tests.ps1
- tests/Unit/Public/New-ObjectNotFoundException.Tests.ps1
- tests/Unit/Public/Remove-CommonParameter.Tests.ps1
- tests/Unit/Public/Test-DscParameterState.Tests.ps1
- tests/Unit/Public/Test-IsNanoServer.Tests.ps1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.common/78)
> Fix missing tasks module

- CHANGELOG.md
- source/Public/Get-LocalizedData.ps1
- source/Public/Get-LocalizedDataForInvariantCulture.ps1
- tests/Unit/Public/Get-LocalizedDataForInvariantCulture.Tests.ps1
This fixes the issue of loading the module when the Globalization-mode is invariant, and creating non-invariant CultureInfo forbidden.
This is to fix the dotnet change, mostly affecting GC on Linux.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.common/80)
> adding some fixes to Get-LocalizedData

- CHANGELOG.md
- README.md
- source/Public/Assert-ElevatedUser.ps1
- source/en-US/DscResource.Common.strings.psd1
- tests/Unit/Public/Assert-ElevatedUser.Tests.ps1
Moved `Assert-ElevatedUser` from a private function in SqlServerDsc to a public function in DscResource.Common
Original issue logged in SqlServerDsc by @johlju [Issue #1797](https://github.com/dsccommunity/SqlServerDsc/issues/1797)
- Fixes #82
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.common/84)
> Added public function Assert-ElevatedUser

- CHANGELOG.md
- source/Public/Assert-ElevatedUser.ps1
- source/en-US/DscResource.Common.strings.psd1
- tests/Unit/Public/Assert-ElevatedUser.Tests.ps1
- `Assert-ElevatedUser`
- Renamed the localized string key name and prepared the localized string
file to be able to distinguish which key belong to which command.
None. Just cleanup.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.common/86)
> `Assert-ElevatedUser`: Minor change to localization key name

- CHANGELOG.md
- README.md
- source/Public/Test-IsNumericType.ps1
- tests/Unit/Public/Assert-ElevatedUser.Tests.ps1
- tests/Unit/Public/Test-IsNumericType.Tests.ps1
Moved `Test-IsNumericType` from a private function in SqlServerDsc to a public function in DscResource.Common
Original issue logged in SqlServerDsc by @johlju [Issue #1795](https://github.com/dsccommunity/SqlServerDsc/issues/1795)
- Fixes #87
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.common/88)
> Added Public Function Test-IsNumericType

- CHANGELOG.md
- tests/Unit/Private/Assert-RequiredCommandParameter.Tests.ps1
- tests/Unit/Private/Test-DscObjectHasProperty.Tests.ps1
- tests/Unit/Private/Test-DscPropertyState.Tests.ps1
- tests/Unit/Public/Assert-BoundParameter.Tests.ps1
- tests/Unit/Public/Assert-ElevatedUser.Tests.ps1
- tests/Unit/Public/Assert-IPAddress.Tests.ps1
- tests/Unit/Public/Assert-Module.Tests.ps1
- tests/Unit/Public/Compare-DscParameterState.Tests.ps1
- tests/Unit/Public/Compare-ResourcePropertyState.Tests.ps1
- tests/Unit/Public/ConvertFrom-DscResourceInstance.Tests.ps1
- tests/Unit/Public/ConvertTo-CimInstance.Tests.ps1
- tests/Unit/Public/ConvertTo-Hashtable.Tests.ps1
- tests/Unit/Public/Get-ComputerName.Tests.ps1
- tests/Unit/Public/Get-LocalizedData.Tests.ps1
- tests/Unit/Public/Get-LocalizedDataForInvariantCulture.Tests.ps1
- tests/Unit/Public/Get-TemporaryFolder.Tests.ps1
- tests/Unit/Public/New-InvalidArgumentException.Tests.ps1
- tests/Unit/Public/New-InvalidDataException.Tests.ps1
- tests/Unit/Public/New-InvalidOperationException.Tests.ps1
- tests/Unit/Public/New-InvalidResultException.Tests.ps1
- tests/Unit/Public/New-NotImplementedException.Tests.ps1
- tests/Unit/Public/New-ObjectNotFoundException.Tests.ps1
- tests/Unit/Public/Remove-CommonParameter.Tests.ps1
- tests/Unit/Public/Test-AccountRequirePassword.Tests.ps1
- tests/Unit/Public/Test-DscParameterState.Tests.ps1
- tests/Unit/Public/Test-IsNanoServer.Tests.ps1
- tests/Unit/Public/Test-IsNumericType.Tests.ps1
- Fixed unit tests to easier run test both from command line and inside
Visual Studio Code.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.common/95)
> Fix unit tests

- CHANGELOG.md
- README.md
- source/Public/Find-Certificate.ps1
- source/en-US/DscResource.Common.strings.psd1
- tests/Unit/Public/Find-Certificate.Tests.ps1
Moved `Find-Certificate` from a utility function in CertificateDsc.Common.psm1 to a public function in DscResource.Common. 
Related to [CertificateDsc Issue #272](https://github.com/dsccommunity/CertificateDsc/issues/272)
- Fixes #100 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Common/101)
> Added Public Function Find-Certificate

- CHANGELOG.md
- README.md
- source/Public/Get-EnvironmentVariable.ps1
- source/Public/Get-PSModulePath.ps1
- tests/Unit/Public/Get-EnvironmentVariable.Tests.ps1
- tests/Unit/Public/Get-PSModulePath.Tests.ps1
- New public commands.
- `Get-EnvironmentVariable` - Get a specific environment variable from a
specific environment variable target.
- `Get-PSModulePath` - Get the the PSModulePath from one or more environment
variable targets - [Issue #103](https://github.com/dsccommunity/DscResource.Common/issues/103)
- Fixes #103
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Common/104)
> Add public commands `Get-PSModulePath` and `Get-EnvironmentVariable`

- CHANGELOG.md
- Resolve-Dependency.ps1
- Resolve-Dependency.psd1
- build.ps1
- source/Public/Get-LocalizedData.ps1
- tests/Unit/Public/Get-LocalizedData.Tests.ps1
- Updated the pipelines files for resolving dependencies.
- `Get-LocalizedData`
- Refactored to simplify execution and debugging. The command previously
used a steppable pipeline (proxies `Import-LocalizedData`), that was
removed since it was not possible to use the command in a pipeline.
It just made it more complex and harder to debug. There are more
debug messages added to hopefully simplify solving some hard to find
edge cases bugs.
- Fixes #108 
- Fixes #74 
- Fixes #37  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …
> `Get-LocalizationData`: Refactor command

- CHANGELOG.md
- build.yaml
- source/Public/Set-PSModulePath.ps1
- tests/Unit/Public/Set-PSModulePath.Tests.ps1
- `Set-PSModulePath`
- A new parameters set takes two parameters `FromTarget` and `ToTarget`
that can copy from omne target to the other (issue #102).
- A new parameter `PassThru` that, if specified, returns the path that
was set.
- A meta task now removes the built module from the session if it is imported.
- Fixes #102
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Common/114)
> Set-PSModulePath: New parameter set

- CHANGELOG.md
- source/Public/New-ArgumentException.ps1
- source/Public/New-Exception.ps1
- source/Public/New-InvalidDataException.ps1
- source/Public/New-InvalidOperationException.ps1
- source/Public/New-InvalidResultException.ps1
- source/Public/New-NotImplementedException.ps1
- source/Public/New-ObjectNotFoundException.ps1
- source/WikiSource/Home.md
- tests/Unit/Public/New-ArgumentException.Tests.ps1
- tests/Unit/Public/New-Exception.Tests.ps1
- tests/Unit/Public/New-InvalidOperationException.Tests.ps1
- tests/Unit/Public/New-NotImplementedException.Tests.ps1
- Wiki source file HOME was modified to not link to README for help after
command documentation now is in the wiki.
- `New-Exception`
- New command that creates and returns an `[System.Exception]`.
- `New-ArgumentException`
- Now takes a parameter `PassThru` that returns the error record that was
created (and does not throw).
- Now has a command alias `New-InvalidArgumentException` and the command
was renamed to match the exception name.
- `New-InvalidOperationException`
- Now takes a parameter `PassThru` that returns the error record that was
created (and does not throw) ([issue #98](https://github.com/dsccommunity/DscResource.Common/issues/98)).
- `New-InvalidResultException`
- Now takes a parameter `PassThru` that returns the error record that was
created (and does not throw).
- …
> Add `New-Exception`, and `PassThru` parameter to exception commands

- CHANGELOG.md
- source/Public/Compare-DscParameterState.ps1
- tests/Unit/Public/Compare-DscParameterState.Tests.ps1
- `Compare-DscParameterState`
- Add support for `DesiredValues` (and `CurrentValues`) to pass a value,
e.g a hashtable, that includes a property with the type `[System.Collections.Specialized.OrderedDictionary]`
or an array of `[System.Collections.Specialized.OrderedDictionary]` ([issue #57](https://github.com/dsccommunity/DscResource.Common/issues/57)).
- Fixes #57
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Common/1 …
> Compare-DscParameterState: Add support for OrderedDictionary type

- CHANGELOG.md
- source/Public/New-ArgumentException.ps1
- source/Public/New-ErrorRecord.ps1
- source/Public/New-InvalidDataException.ps1
- source/Public/New-InvalidOperationException.ps1
- source/Public/New-InvalidResultException.ps1
- source/Public/New-NotImplementedException.ps1
- source/Public/New-ObjectNotFoundException.ps1
- tests/Unit/Public/New-ErrorRecord.Tests.ps1
- `New-ErrorRecord`
- New command that creates and returns an `[System.Management.Automation.ErrorRecord]`
([issue #99](https://github.com/dsccommunity/DscResource.Common/issues/99)).
- `New-ArgumentException`
- Now uses the new command `New-ErrorRecord`.
- `New-InvalidDataException`
- Now uses the new command `New-ErrorRecord`.
- `New-InvalidOperationException`
- Now uses the new command `New-ErrorRecord`.
- `New-InvalidResultException`
- Now uses the new command `New-ErrorRecord`.
- `New-NotImplementedException`
- Now uses the new command `New-ErrorRecord`.
- `New-ObjectNotFoundException`
- Now uses the new command `New-ErrorRecord`.
- Fixes #99 
(if …
> Add new command New-ErrorRecord

- CHANGELOG.md
- source/Public/Get-PSModulePath.ps1
- tests/Unit/Public/Get-PSModulePath.Tests.ps1
- `Get-PSModulePath`
- Can now return the individual module path for different scopes when
using the parameter `-Scope`. If no parameter is specified the command
return the path for the scope CurrentUser.
- `Get-PSModulePath`
- Was using the wrong path separator on Linux and macOS.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Common/120)
> Get-PSModulePath: Improve the command with Scope

- CHANGELOG.md
- source/Public/Get-LocalizedData.ps1
- tests/Unit/Public/Get-LocalizedData.Tests.ps1
- `Get-LocalizedData`
- Wrongly returned one or more boolean values in addition to
the localized string array. This was becuase the return value
was not handled when calling `Add()` and `Remove()` methods of
`$PSBoundParameters` so it was returned to the pipeline.
None. Was reported in https://github.com/dsccommunity/DscResource.Base/issues/7#issuecomment-2072729109.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Common/ …
> Get-LocalizedData: Fix returning additional (wrong) values to pipeline

- CHANGELOG.md
- source/Public/Get-PSModulePath.ps1
- source/Public/Get-UserName.ps1
- source/en-US/DscResource.Common.strings.psd1
- tests/Integration/Public/Set-PSModulePath.Tests.ps1
- tests/Unit/Public/Get-UserName.Tests.ps1
- Public command:
- `Get-UserName` - get current user name cross platform.
- `Get-PSModulePath`
- Throws an exception if the My Documents folder cannot be found when
calling the command with the scope `CurrentUser` (issue #122).
- Fixes #122
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Common/125)
> `Get-PSModulePath`: Throw exception on missing My Documents folder

- CHANGELOG.md
- source/Public/Assert-ElevatedUser.ps1
- tests/Unit/Public/Assert-ElevatedUser.Tests.ps1
Add parameter to `Assert-ElevatedUser` to allow use of custom error messages. Backward compatible with existing as default value is the old error message value. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Common/129)
> `Assert-ElevatedUser` - Add custom error message parameter

- CHANGELOG.md
- source/Public/Get-RegistryPropertyValue.ps1
- tests/Unit/Public/Get-RegistryPropertyValue.Tests.ps1
- `Get-RegistryPropertyValue`
- Current implementation was not safe and could throw an exception if
the property did not exist, even if `-ErrorAction 'SilentlyContinue`
was passed. This was fixed by using `Get-ItemProperty` instead of
`Get-ItemPropertyValue` ([issue #139](https://github.com/dsccommunity/DscResource.Common/issues/139#issuecomment-2708847681).
- Fixes #139
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Com …
> Fix `Get-RegistryPropertyValue` to handle non-existent property safely

- CHANGELOG.md
- azure-pipelines.yml
- source/Public/Get-FileProductVersion.ps1
- source/en-US/DscResource.Common.strings.psd1
- tests/Unit/Public/Get-FileProductVersion.Tests.ps1
- DscResource.Common
- Public command:
- `Get-FileProductVersion` - Get the product version of a file.
None. Helps with review comment for PR https://github.com/dsccommunity/SqlServerDsc/pull/2083
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Common/148)
> `Get-FileProductVersion`: Add public command

- CHANGELOG.md
- source/Private/Clear-ZeroedEnumPropertyValue.ps1
- source/Public/Get-DscProperty.ps1
- tests/Unit/Private/Clear-ZeroedEnumPropertyValue.Tests.ps1
- tests/Unit/Public/Get-DscProperty.Tests.ps1
Add new optional parameter `IgnoreZeroEnumValue` to `Get-DscProperty`.
- Fixes #150 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Common/151)
> `Get-DscProperty`: Add optional switch parameter `IgnoreZeroEnumValue`

- CHANGELOG.md
- source/Public/Format-Path.ps1
- tests/Unit/Public/Format-Path.Tests.ps1
Add `ExpandEnvironmentVariable` to `Format-Path`. 
- Fixes #147 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Common/152)
> `Format-Path` add `ExpandEnvironmentVariable` Parameter

- CHANGELOG.md
- source/Private/Assert-RequiredCommandParameter.ps1
- source/Public/Assert-BoundParameter.ps1
- tests/Integration/Commands/Assert-BoundParameter.Integration.Tests.ps1
- tests/Integration/Commands/Get-ComputerName.Integration.Tests.ps1
- tests/Integration/Commands/Set-DscMachineRebootRequired.Integration.Tests.ps1
- tests/Integration/Commands/Set-PSModulePath.Integration.Tests.ps1
- tests/Unit/Private/Assert-RequiredCommandParameter.Tests.ps1
- tests/Unit/Private/Clear-ZeroedEnumPropertyValue.Tests.ps1
- tests/Unit/Private/Test-DscPropertyIsAssigned.Tests.ps1
- tests/Unit/Public/Assert-BoundParameter.Tests.ps1
- `Assert-BoundParameter`
- Enhanced parameter `IfParameterPresent` to support both string arrays and
hashtables for conditional assertion logic.
- Added alias `IfEqualParameterList` to parameter `IfParameterPresent` for
backward compatibility.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Common/165)
> `Assert-BoundParameter`: Move `IfEqualParameterList` into `IfParameterPresent`

- CHANGELOG.md
- source/Public/Compare-DscParameterState.ps1
- source/Public/Find-Certificate.ps1
- source/Public/Get-LocalizedDataForInvariantCulture.ps1
- source/Public/Test-IsNanoServer.ps1
- source/Public/Test-ModuleExist.ps1
- `Compare-DscParameterState`
- Changed detailed diagnostic messages from `Write-Verbose` to `Write-Debug`
for variable values, type comparisons, and internal diagnostics.
- `Test-ModuleExist`
- Changed module filtering messages from `Write-Verbose` to `Write-Debug`
for internal implementation details.
- `Test-IsNanoServer`
- Changed operating system SKU diagnostic message from `Write-Verbose` to `Write-Debug`.
- `Find-Certificate`
- Changed certificate filter diagnostic message from `Write-Verbose` to `Write-Debug`.
- `Get-LocalizedDataForInvariantCulture`
- Changed file processing message from `Write-Verbose` to `Write-Debug`
for internal diagnostic information.
- Helps with #157 
affects users (if applicable), and …
> Change verbose messages to debug messages

- CHANGELOG.md
- source/Private/Clear-ZeroedEnumPropertyValue.ps1
- source/Private/Test-DscPropertyState.ps1
- source/Public/Assert-BoundParameter.ps1
- source/Public/Compare-DscParameterState.ps1
- source/Public/Compare-ResourcePropertyState.ps1
- source/Public/ConvertFrom-DscResourceInstance.ps1
- source/Public/Find-Certificate.ps1
- source/Public/Get-DscProperty.ps1
- source/Public/Get-UserName.ps1
- source/Public/Remove-CommonParameter.ps1
- source/Public/Test-DscProperty.ps1
Remove some of the slow code in functions used by `DscResource.Base`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Common/172)
> Performance optimizations

- CHANGELOG.md
- source/Private/Clear-ZeroedEnumPropertyValue.ps1
- source/Public/Get-LocalizedDataForInvariantCulture.ps1
- source/Public/New-InvalidDataException.ps1
- source/Public/New-InvalidOperationException.ps1
- source/Public/New-InvalidResultException.ps1
- source/Public/New-NotImplementedException.ps1
- source/Public/New-ObjectNotFoundException.ps1
- tests/Unit/Public/New-InvalidDataException.Tests.ps1
Replace use of throw with ThrowTerminatingError. 
- Fixes #177
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Common/179)
> Replace throw with ThrowTerminatingError in exception handling
