dsccommunity/DscResource.Common

.vscode/settings.json, CHANGELOG.md, README.md, azure-pipelines.yml, source/Public/New-InvalidArgumentException.ps1, source/Public/New-InvalidOperationException.ps1, source/Public/New-InvalidResultException.ps1, source/Public/New-NotImplementedException.ps1, source/Public/New-ObjectNotFoundException.ps1, source/Public/Test-DscParameterState.ps1
- Added more function documentation to the README.md.
- Fix minor style issue in functions.
- Changed the VS Code project settings to trim trailing whitespace for
markdown files too.
- Changed the VS Code project setting `pipelineIndentationStyle` to use
the correct style.
- The deploy step is no longer run on forks.
- Azure Pipelines will no longer trigger on changes to just the CHANGELOG.md.
Fixes #6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.common/7)
=> Update documentation in the README.md

CHANGELOG.md, README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.common/8)
=> Update README.md with section "How to implement"

CHANGELOG.md, README.md, source/Public/Assert-Module.ps1, source/en-US/DscResource.Common.psd1, tests/Unit/Public/Assert-Module.Tests.ps1, tests/Unit/Public/New-InvalidArgumentException.Tests.ps1, tests/Unit/Public/New-ObjectNotFoundException.Tests.ps1
- Added the function `Assert-Module`.
- Updated the localized strings to have the unique id according to style
guideline.
Fixes #15
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.common/14)
=> Add function Assert-Module

CHANGELOG.md, README.md, source/Public/Assert-Module.ps1, tests/Unit/Public/Assert-Module.Tests.ps1
This PR adds the `ImportModule` parameter to the `Assert-Module` function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.common/17)
=> Assert-Module: Add ImportModule Parameter

.github/ISSUE_TEMPLATE/General.md, .github/ISSUE_TEMPLATE/Problem_with_module.md, .github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, GitVersion.yml, README.md, azure-pipelines.yml, source/Public/Assert-BoundParameter.ps1, source/en-US/DscResource.Common.psd1, tests/Unit/Public/Assert-BoundParameter.Tests.ps1
- Added the cmdlet `Assert-BoundParameter`. _This cndlet comes from_
_ComputerManagementDsc._
- Added GitHub templates in the repository to help contributors.
- Only run CI pipeline on branch `master` when there are changes to files
inside the `source` folder.
- The regular expression for `minor-version-bump-message` in the file
`GitVersion.yml` was changed to only raise minor version when the
commit message contain the word `add`, `adds`, `minor`, `feature`,
or `features`.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.common/20)
=> Adds the cmdlet Assert-BoundParameter

CHANGELOG.md, azure-pipelines.yml
- Fixed the pipeline paths trigger.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.common/21)
=> Fixed the pipeline paths trigger

CHANGELOG.md, README.md, source/Public/Get-TemporaryFolder.ps1, tests/Unit/Public/Get-TemporaryFolder.Tests.ps1
- Added the cmdlet `Get-TemporaryFolder`. _This cmdlet comes from_
_SqlServerDsc._
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.common/22)
=> Adds the cmdlet Get-TemporaryFolder

CHANGELOG.md, README.md
- Update the README.md with new cmdlet documentation format.
- Fixes #12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.common/24)
=> Update the README.md with new cmdlet documentation format

CHANGELOG.md, tests/Unit/Public/Test-DscParameterState.Tests.ps1
- The code in the unit tests for `Test-DscParameterState` is now closer
following the style guideline.
*This is the unit tests that was removed from the module SqlServerDsc, so instead of making the changes twice I moved it here. Just style guideline changes.*
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.common/25)
=> Unit tests for Test-DscParameterState follow style guideline

CHANGELOG.md, README.md, source/Public/Assert-IPAddress.ps1, source/en-US/DscResource.Common.psd1, tests/Unit/Public/Assert-IPAddress.Tests.ps1
Added Assert-IPAddress function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.common/27)
=> Adds cmdlet Assert-IPAddress

CHANGELOG.md, azure-pipelines.yml, source/Private/Test-DscObjectHasProperty.ps1, tests/Unit/Private/Test-DscObjectHasProperty.Tests.ps1
- Add missing private function Test-DscObjectHasProperty
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.common/30)
=> Add missing private function Test-DscObjectHasProperty

CHANGELOG.md, build.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.common/35)
=> Fixes a problem with the latest ModuleBuild

CHANGELOG.md, README.md, RequiredModules.psd1, source/Public/New-InvalidDataException.ps1, source/Public/Set-DscMachineRebootRequired.ps1, tests/Integration/Public/Set-DscMachineRebootRequired.Tests.ps1, tests/Unit/Public/New-InvalidDataException.Tests.ps1
This PR adds two functions used by xPSDesiredStateConfiguration: 
- Set-DscMachineRebootRequired
- New-InvalidDataException
- Fixes #42
- Fixes #43
@johlju - would you mind reviewing for me when you have time?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.common/44)
=> Added Set-DscMachineRebootRequired and New-InvalidDataException

CHANGELOG.md, README.md, build.yaml, source/Public/Test-IsNumericType.ps1, tests/Unit/Public/Test-IsNumericType.Tests.ps1
- DscResource.Common
- Now builds the module into a separate folder `output/builtModule`.
- `Test-IsNumericType`
- Now handles arrays correctly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.common/90)
=> `Test-IsNumericType`: Now handles arrays correctly

CHANGELOG.md, README.md
- `Assert-BoundParameter`
- Fixed example in documentation that were referencing an invalid command name.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Common/107)
=> SqlServerDsc: Fix documentation

CHANGELOG.md, source/Public/Get-LocalizedData.ps1
- `Get-LocalizedData`
- One debug message was wrongly using a format operator (issue #111).
- Fixes #111
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Common/112)
=> `Get-LocalizedData`: Fix debug message

CHANGELOG.md, source/Public/Assert-Module.ps1, source/Public/Test-ModuleExist.ps1, tests/Unit/Public/Test-ModuleExist.Tests.ps1
- `Test-ModuleExist`
- Checks if a PowerShell module with a specified name is available in a
PSModulePath.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Common/121)
=> `Test-ModuleExist`: New public command

.vscode/analyzersettings.psd1, CHANGELOG.md, RequiredModules.psd1, build.yaml, source/Public/Assert-ElevatedUser.ps1, source/Public/Set-DscMachineRebootRequired.ps1
DscResource.ScriptAnalyzer Rules preview has found some issues in this module. 
This enables using the preview module, fixes the issues, cleans up the config file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Common/134)
=> Fix HQRM with preview DscResource.ScriptAnalyzer Rules

CHANGELOG.md, source/Enum/BoundParameterBehavior.ps1, source/Private/Assert-RequiredCommandParameter.ps1, source/Public/Assert-BoundParameter.ps1, source/en-US/DscResource.Common.strings.psd1, tests/Unit/Private/Assert-RequiredCommandParameter.Tests.ps1, tests/Unit/Public/Assert-BoundParameter.Tests.ps1
Extend `Assert-RequiredCommandParameter` RequiredParameter to either match All (default) or AtLeastOnce parameter.
- Fixes #136 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Common/137)
=> Extend `Assert-RequiredCommandParameter` RequiredParameter

CHANGELOG.md, source/Public/Format-Path.ps1, source/en-US/DscResource.Common.strings.psd1, tests/Unit/Public/Format-Path.Tests.ps1
- DscResource.Common
- Public command:
- `Format-Path` - Format a file system path based on the operating
system and specified parameters.
None. Moving command from SqlServerDsc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Common/145)
=> `Format-Path`: Add command for path normalization

CHANGELOG.md, source/Public/Compare-DscParameterState.ps1
- Fixes #157 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Common/175)
=> Final Verbose to Debug changes

CHANGELOG.md, source/DscResource.Common.psd1, source/Public/Get-LocalizedData.ps1, source/Public/Get-LocalizedDataForInvariantCulture.ps1, source/Public/New-ArgumentException.ps1, source/Public/New-ErrorRecord.ps1, source/Public/New-Exception.ps1, source/Public/New-InvalidDataException.ps1, source/Public/New-InvalidOperationException.ps1, source/Public/New-InvalidResultException.ps1, source/Public/New-NotImplementedException.ps1, source/Public/New-ObjectNotFoundException.ps1
Replace New-Object with ::new(), make PS 5.0 review to use ::new().
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Common/176)
=> PS 5.0 required; replace New-Object with ::new(); streamline errors
